// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdrbJITFkPuXI9Hk27I9Vn2GtbDXd55eE',
    appId: '1:817778815624:web:bc2e3c43aec0f00774253d',
    messagingSenderId: '817778815624',
    projectId: 'twitch-clone-25998',
    authDomain: 'twitch-clone-25998.firebaseapp.com',
    storageBucket: 'twitch-clone-25998.appspot.com',
    measurementId: 'G-8PQXPPQ2F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsghIM5H7T-5sMd_2aAEjaj9nCHMMqSO4',
    appId: '1:817778815624:android:3b7a90da546fe82074253d',
    messagingSenderId: '817778815624',
    projectId: 'twitch-clone-25998',
    storageBucket: 'twitch-clone-25998.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw3_8wKc43bH9EmLDrdNZ-inmeRODKjPU',
    appId: '1:817778815624:ios:b5e8850a3cd0c73574253d',
    messagingSenderId: '817778815624',
    projectId: 'twitch-clone-25998',
    storageBucket: 'twitch-clone-25998.appspot.com',
    iosClientId: '817778815624-rkng8g27i8lksqmtkn5ibeouj1dpjh8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoStreamingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw3_8wKc43bH9EmLDrdNZ-inmeRODKjPU',
    appId: '1:817778815624:ios:b5e8850a3cd0c73574253d',
    messagingSenderId: '817778815624',
    projectId: 'twitch-clone-25998',
    storageBucket: 'twitch-clone-25998.appspot.com',
    iosClientId: '817778815624-rkng8g27i8lksqmtkn5ibeouj1dpjh8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoStreamingApp',
  );
}
